name: CI/CD
on:
  push:
    tags: [ v* ]

jobs:
  CI:
    uses: ./.github/workflows/ci.yml

  CD:
    name: Publish to crates.io
    needs: [ CI ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: speelbarrow/checkout-and-setup@v0
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
